"""Turn a generated summary into a file the user can keep.

The summariser already produces structured output - a headline paragraph, key
points, and provenance about what it read. That structure is what makes an export
worth more than "copy the blob into a .txt": the bullets land as real list items
in the DOCX, and the same layout is reproduced in the PDF and the text file.

PDF is produced by rendering the DOCX through the same converter the document
export uses, so a summary follows the app's existing PDF pipeline (fonts,
conversion fallbacks and all) instead of introducing a second one.
"""

import io
import logging
from datetime import datetime

import docx
from docx.shared import Pt, Inches, RGBColor

from RapidDoc.backend.app.services.pdf_converter import convert_docx_bytes_to_pdf

logger = logging.getLogger(__name__)

SUPPORTED_FORMATS = ("txt", "docx", "pdf")

ACCENT = RGBColor(0x25, 0x63, 0xEB)
MUTED = RGBColor(0x64, 0x74, 0x8B)


def _clean_points(points, limit: int = 8) -> list:
    """De-duplicate and trim the key points to something a reader will finish."""
    seen = set()
    cleaned = []
    for point in points or []:
        text = str(point or "").strip()
        if not text:
            continue
        # A model will happily return the same bullet twice under different
        # capitalisation; in a one-page summary that reads as padding.
        key = text.lower().rstrip(".")
        if key in seen:
            continue
        seen.add(key)
        cleaned.append(text)
        if len(cleaned) >= limit:
            break
    return cleaned


def _sections(payload: dict) -> list:
    """The body of the export, in reading order: what was read, then the gist."""
    sections = []

    summary = (payload.get("summary") or "").strip()
    if summary:
        sections.append(("Summary", [summary], False))

    points = _clean_points(payload.get("key_points"))
    if points:
        sections.append(("Key points", points, True))

    return sections


def _meta_lines(payload: dict) -> list:
    lines = []
    source = payload.get("source")
    if source:
        lines.append(f"Source: {source}")
    engine = payload.get("engine")
    if engine:
        lines.append(f"Generated by: {engine}")
    characters = payload.get("characters")
    if characters:
        lines.append(f"Characters read: {characters:,}")
    lines.append(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}")
    return lines


def build_summary_txt(payload: dict, title: str) -> bytes:
    lines = [title, "=" * len(title), ""]
    lines.extend(_meta_lines(payload))
    lines.append("")

    for heading, items, is_list in _sections(payload):
        lines.append(heading)
        lines.append("-" * len(heading))
        for item in items:
            lines.append(f"  - {item}" if is_list else item)
            if not is_list:
                lines.append("")
        lines.append("")

    return "\n".join(lines).encode("utf-8")


def build_summary_docx(payload: dict, title: str) -> bytes:
    d = docx.Document()

    normal = d.styles["Normal"]
    normal.font.name = "Calibri"
    normal.font.size = Pt(11)

    d.add_heading(title, level=0)

    for line in _meta_lines(payload):
        d.add_paragraph(line).runs[0].font.color.rgb = MUTED

    for heading, items, is_list in _sections(payload):
        d.add_heading(heading, level=1)
        if is_list:
            # The real list style, so the bullets are bullets in Word rather than
            # a paragraph that happens to start with a dash.
            d.add_paragraph(items[0], style="List Bullet")
            for item in items[1:]:
                d.add_paragraph(item, style="List Bullet")
        else:
            paragraph = d.add_paragraph()
            run = paragraph.add_run(items[0])
            run.font.size = Pt(11.5)
            run.font.color.rgb = ACCENT

    buf = io.BytesIO()
    d.save(buf)
    return buf.getvalue()


def build_summary_pdf(payload: dict, title: str) -> bytes:
    """Render through the shared DOCX -> PDF converter.

    Built in memory rather than via temp files because a summary export is
    triggered one-off from the editor and there is no path worth keeping.
    """
    docx_bytes = build_summary_docx(payload, title)
    return convert_docx_bytes_to_pdf(docx_bytes)


def build_summary_bytes(fmt: str, payload: dict, title: str) -> tuple:
    """Return ``(bytes, filename, media_type)`` for a summary export."""
    fmt = (fmt or "txt").lower().strip()
    if fmt not in SUPPORTED_FORMATS:
        raise ValueError(f"Unsupported summary format: {fmt}")

    stem = (title or "summary").rsplit(".", 1)[0]
    # Keep the name filesystem- and header-safe: it is about to be handed to a
    # Content-Disposition header.
    safe = "".join(ch if ch.isalnum() or ch in " -_" else " " for ch in stem).strip() or "summary"
    safe = "_".join(safe.split())

    if fmt == "txt":
        return build_summary_txt(payload, title), f"{safe}.txt", "text/plain; charset=utf-8"
    if fmt == "docx":
        return (build_summary_docx(payload, title),
                f"{safe}.docx",
                "application/vnd.openxmlformats-officedocument.wordprocessingml.document")
    return build_summary_pdf(payload, title), f"{safe}.pdf", "application/pdf"