"""Turn a generated summary into a file the user can keep.

Supports exporting as:
  1. .md   - Original structured Markdown generated by the backend
  2. .txt  - Clean plain text with Markdown syntax cleanly stripped and formatting preserved
  3. .docx - Formatted Word document with headings and bullets
  4. .pdf  - Rendered PDF via DOCX conversion pipeline
"""

import io
import logging
import re
from datetime import datetime

import docx
from docx.shared import Inches, Pt, RGBColor

from RapidDoc.backend.app.services.pdf_converter import convert_docx_bytes_to_pdf

logger = logging.getLogger(__name__)

SUPPORTED_FORMATS = ("md", "txt", "docx", "pdf")

ACCENT = RGBColor(0x25, 0x63, 0xEB)
MUTED = RGBColor(0x64, 0x74, 0x8B)


def _clean_markdown_to_plain_text(markdown_text: str) -> str:
    """Convert Markdown into clean, readable plain text.
    
    Removes syntax (#, **, *, backticks) while preserving headings, paragraphs,
    lists, and overall layout.
    """
    if not markdown_text:
        return ""

    lines = markdown_text.splitlines()
    plain_lines = []

    for line in lines:
        stripped = line.strip()
        if not stripped:
            plain_lines.append("")
            continue

        # Convert # Headings to clean plain title/heading
        if stripped.startswith("#"):
            heading_content = re.sub(r"^#+\s*", "", stripped)
            # Remove any inline markdown
            heading_content = re.sub(r"\*\*([^*]+)\*\*", r"\1", heading_content)
            heading_content = re.sub(r"\*([^*]+)\*", r"\1", heading_content)
            plain_lines.append(heading_content.upper() if stripped.startswith("# ") else heading_content)
            if stripped.startswith("# "):
                plain_lines.append("=" * min(len(heading_content), 60))
            elif stripped.startswith("## "):
                plain_lines.append("-" * min(len(heading_content), 50))
            continue

        # Strip bold and italics: **bold** or *italic*
        cleaned_line = re.sub(r"\*\*([^*]+)\*\*", r"\1", line)
        cleaned_line = re.sub(r"\*([^*]+)\*", r"\1", cleaned_line)
        cleaned_line = re.sub(r"__([^_]+)__", r"\1", cleaned_line)
        cleaned_line = re.sub(r"_([^_]+)_", r"\1", cleaned_line)

        # Strip inline code backticks: `code`
        cleaned_line = re.sub(r"`([^`]+)`", r"\1", cleaned_line)

        # Strip block backticks: ```
        if cleaned_line.strip().startswith("```"):
            continue

        plain_lines.append(cleaned_line)

    return "\n".join(plain_lines).strip()


def _meta_lines(payload: dict) -> list:
    lines = []
    source = payload.get("source")
    if source:
        lines.append(f"Source: {source}")
    engine = payload.get("engine")
    if engine:
        lines.append(f"Generated by: {engine}")
    characters = payload.get("characters")
    if characters:
        lines.append(f"Characters read: {characters:,}")
    lines.append(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}")
    return lines


def build_summary_md(payload: dict, title: str) -> bytes:
    """Export the original, complete Markdown summary returned by the backend."""
    raw_summary = (payload.get("summary") or "").strip()
    if not raw_summary:
        raw_summary = f"# Document Summary: {title}\n\nNo summary available."

    # If the summary is already fully formatted Markdown, return it
    if raw_summary.startswith("#"):
        return raw_summary.encode("utf-8")

    # Otherwise synthesize valid Markdown from the payload
    md_lines = [
        f"# Document Summary: {title}",
        "",
        "## Overview",
        raw_summary,
        "",
    ]
    points = payload.get("key_points") or []
    if points:
        md_lines.append("## Key Points")
        for pt in points:
            md_lines.append(f"- {pt}")
        md_lines.append("")

    return "\n".join(md_lines).encode("utf-8")


def build_summary_txt(payload: dict, title: str) -> bytes:
    """Export clean plain text with Markdown syntax stripped and structure preserved."""
    raw_summary = (payload.get("summary") or "").strip()

    if raw_summary.startswith("#") or "##" in raw_summary:
        plain_body = _clean_markdown_to_plain_text(raw_summary)
        return plain_body.encode("utf-8")

    # Fallback structure for plain prose payloads
    lines = [title, "=" * len(title), ""]
    lines.extend(_meta_lines(payload))
    lines.append("")

    lines.append("SUMMARY")
    lines.append("-" * 7)
    lines.append(raw_summary)
    lines.append("")

    points = payload.get("key_points") or []
    if points:
        lines.append("KEY POINTS")
        lines.append("-" * 10)
        for pt in points:
            lines.append(f"  - {pt}")
        lines.append("")

    return "\n".join(lines).encode("utf-8")


def build_summary_docx(payload: dict, title: str) -> bytes:
    """Build Word document from Markdown or structured summary payload."""
    d = docx.Document()

    normal = d.styles["Normal"]
    normal.font.name = "Calibri"
    normal.font.size = Pt(11)

    raw_summary = (payload.get("summary") or "").strip()

    if raw_summary.startswith("#") or "##" in raw_summary:
        for line in raw_summary.splitlines():
            s = line.strip()
            if not s:
                continue
            if s.startswith("# "):
                h = d.add_heading(s[2:], level=0)
            elif s.startswith("## "):
                h = d.add_heading(s[3:], level=1)
            elif s.startswith("### "):
                h = d.add_heading(s[4:], level=2)
            elif s.startswith("- ") or s.startswith("* "):
                bullet_text = s[2:]
                bullet_clean = re.sub(r"\*\*([^*]+)\*\*", r"\1", bullet_text)
                d.add_paragraph(bullet_clean, style="List Bullet")
            else:
                clean_text = re.sub(r"\*\*([^*]+)\*\*", r"\1", s)
                p = d.add_paragraph(clean_text)
    else:
        d.add_heading(title, level=0)
        for line in _meta_lines(payload):
            d.add_paragraph(line).runs[0].font.color.rgb = MUTED
        d.add_heading("Summary", level=1)
        p = d.add_paragraph()
        run = p.add_run(raw_summary)
        run.font.size = Pt(11.5)
        run.font.color.rgb = ACCENT

        points = payload.get("key_points") or []
        if points:
            d.add_heading("Key points", level=1)
            for pt in points:
                d.add_paragraph(str(pt), style="List Bullet")

    buf = io.BytesIO()
    d.save(buf)
    return buf.getvalue()


def build_summary_pdf(payload: dict, title: str) -> bytes:
    """Render through the shared DOCX -> PDF converter."""
    docx_bytes = build_summary_docx(payload, title)
    return convert_docx_bytes_to_pdf(docx_bytes)


def build_summary_bytes(fmt: str, payload: dict, title: str) -> tuple:
    """Return ``(bytes, filename, media_type)`` for a summary export."""
    fmt = (fmt or "txt").lower().strip()
    if fmt not in SUPPORTED_FORMATS:
        raise ValueError(f"Unsupported summary format: {fmt}")

    stem = (title or "summary").rsplit(".", 1)[0]
    safe = "".join(ch if ch.isalnum() or ch in " -_" else " " for ch in stem).strip() or "summary"
    safe = "_".join(safe.split())

    if fmt == "md":
        return build_summary_md(payload, title), f"{safe}.md", "text/markdown; charset=utf-8"
    if fmt == "txt":
        return build_summary_txt(payload, title), f"{safe}.txt", "text/plain; charset=utf-8"
    if fmt == "docx":
        return (
            build_summary_docx(payload, title),
            f"{safe}.docx",
            "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        )
    return build_summary_pdf(payload, title), f"{safe}.pdf", "application/pdf"